### ISSUE TITLE
Nest Hello video feed incorrect aspect ratio

### ISSUE THREAD

**Issue by muzzymate** [Brandawg93/homebridge-nest-cam#111]
**Describe the bug**

Somewhere between version 3.2.0 and 3.2.2, the video feed from my Nest Hello doorbell camera begins outputting stretched video in 16x9 format instead of 4x3. Version 3.2.0 is the last version that outputs 4x3 video for me.

**To Reproduce**

1. Install version 3.3.0 or 3.2.2.
2. View camera feed in Home app. Video output is stretched and in 16x9 output. 
3. Revert to version 3.2.0 (version 3.2.1 will not start a stream on my system for whatever reason).
4. View camera feed in Home app. Video output is correctly displayed in 4x3 output. 

**Expected behavior**

Video output for Nest Hello cameras output in 4x3 aspect ration. 

On what OS are you running homebridge:  Windows 10 Version 1903 (OS Build 18362.836); NodeJS v12.17.0
What camera types are having issues:  Nest Hello Doorbell Camera
Does this issue occur consistently or randomly: consistently
If applicable, what was the last version that worked properly: 3.2.0

**Comment by Brandawg93** [comment]
That's odd. Nothing has changed between these versions that would change aspect ratio. I've also tested my doorbell and asked others on v3.3.0 and no one else is having this issue. Maybe try removing homebridge from the Home app and adding it back.

**Comment by muzzymate** [comment]
Yeah, that's why I was so confused. I didn't see anything in the release notes that would lead me to believe part of the code was changed that deals with aspect ratio or camera detection.

I did try removing the Windows Homebridge instance and re-add it. Unfortunately, that did not seem to have any noticeable effect. 

I moved Homebridge-Nest-Cam over from Windows Homebridge instance to my Raspberry Pi running the official Homebridge image, on node v12.17.0, and Raspbian GNU/Linux Buster (10). Using 3.3.0 on this Pi, the video feed is stretched. Here I am able to have version 3.2.1 output a video feed for me but it is stretched as well. Version 3.2.0 correctly outputs 4x3 video. So I seem to be having the same results regardless of what platform I am running Homebridge on. 

Below is my config.json block for Homebridge-Nest-Cam. I'll see if I can play around with options in case it has anything to do with my particular combination. I'm going to keep the Windows version on the latest and the Linux version on 3.2.0 for now.

        {
            "googleAuth": {
                "issueToken": "XXXXXXXXXX",
                "cookies": "XXXXXXXXXXX",
                "apiKey": "XXXXXXXXXXXXXXX"
            },
            "ffmpegCodec": "libx264",
            "options": {
                "alertCheckRate": 10,
                "alertCooldownRate": 120,
                "motionDetection": true,
                "streamingSwitch": false,
                "chimeSwitch": false,
                "doorbellAlerts": true,
                "doorbellSwitch": true,
                "audioSwitch": false
            },
            "platform": "Nest-cam"
        }

**Comment by Brandawg93** [comment]
I found some code that could be the culprit. I've published a new test version with it fixed. You can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`. Let me know if that happens to fix your aspect ratio.

**Comment by muzzymate** [comment]
Updated to the test build (3.3.1-test.2) and yes, that fixed my aspect ratio problem. Validated on both the Windows and Linux Homebridge instances. Thank you!

**Comment by Brandawg93** [comment]
That's very interesting.. I've created a new test that outputs the profiles that your camera uses. Could you update to that test and copy that output here? It should say something like `these are the profiles used:` and then a few numbers.

**Comment by muzzymate** [comment]
Hmmm.... I ran the npm command again you listed to try and update, but after restarting Homebridge, I am not seeing the "profiles used" text output. Should the 3.3.1-test.X value increase? When I run the install command, I still receive 2.

**Comment by Brandawg93** [comment]
It should be [v3.3.1-test.3](https://www.npmjs.com/package/homebridge-nest-cam/v/3.3.1-test.3).

**Comment by muzzymate** [comment]
Finally updated. Here is what I get:

these are the profiles used:
9
[ 7, 9, 8 ]

**Comment by Brandawg93** [comment]
Good to know! Thanks for helping me debug this. I'm actually about to publish an update that will allow others to choose their stream quality. Before I do so, I want to make sure all of my changes don't revert your aspect ratio. I've published a new test that includes everything to be included in the next release. Would you mind trying it for me one last time?

**Comment by muzzymate** [comment]
Will do. I'll report back in once the test version updates.  A big huge thank you for figuring out the fix!

**Comment by Brandawg93** [comment]
No Problem! Just let me know when you can.

**Comment by muzzymate** [comment]
Ok, the npm command finally updated to version -test.4 and the camera still streams in the correct aspect ratio.

:-)

**Comment by Brandawg93** [comment]
Great! -test.4 = v3.4.0 so this should now be fixed and released.
