### ISSUE TITLE
Nest Cam app crashing HomeBridge

### ISSUE THREAD

**Issue by geoffreyspencer** [Brandawg93/homebridge-nest-cam#315]
I followed the Troubleshooting page and it did not solve the issue.

After loading successfully all my devices, HomeBridge (using the Homebridge UI plug-in), Homebridge crashes. I have to remove the manual log-in settings from the Config for Nest-cam and Homebridge no longer crashes and restarts indefinitely.

FYI, I have use Smart Key for Google account. I also have the Homebridge Nest app and I do not have any issues. This plug-in has also the API field in the settings that is not in the Nest-cam plug-in. Is that needed now?

This is the error from the log:

 Error: Cannot update txt of service which is not announced yet. Received unannounced for service Homebridge 793B AF95._hap._tcp.local.
    at Responder.handleServiceRecordUpdate (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:410:13)
    at CiaoService.emit (events.js:198:13)
    at Timeout.txtTimer.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/CiaoService.ts:461:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[10/21/2020, 8:40:23 AM] Got SIGTERM, shutting down Homebridge...
[10/21/2020, 8:40:24 AM] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:354:13)
    at MDNSServer.sendOnAllNetworks (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:274:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:235:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:155:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
    at Timer.processTimers (timers.js:222:12)

**Comment by Brandawg93** [comment]
I just published a new version of the plugin (v5.5.0). Try it and let me know if it fixes it. If not, try clearing your homebridge cache. I don't see anything in the log above that specifically says this is a nest-cam issue so it's hard to pinpoint what is going wrong.

**Comment by mikegraben** [comment]
Getting the same error, and have basically blown away my Homebridge setup as a result. :(

-Using the latest plugin
-Cleared my accessories cache
-Removing nest-cam from my config solves the problem

My cams were working fine until I updated the plugin today: homebridge-nest-cam v5.5.2

**Comment by Brandawg93** [comment]
What version of homebridge are you using?

**Comment by mikegraben** [comment]
Up to date with 1.2.3 @Brandawg93 

Homebridge and all my plugins work fine, but as soon as I had the Nest Cam configuration back into my config, the Homebridge crashes begin.  The log shows it finding my cameras, but then I immediately get this:

`[10/27/2020, 1:41:07 AM] [Nest-cam] Configuring accessory Office Cam
[10/27/2020, 1:41:09 AM] Error: Cannot update txt of service which is not announced yet. Received unannounced for service My Homebridge CAD8._hap._tcp.local.
    at Responder.handleServiceRecordUpdate (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:410:13)
    at CiaoService.emit (events.js:198:13)
    at Timeout.txtTimer.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/CiaoService.ts:461:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

Then it does a few more things and shows this:

`[10/27/2020, 1:41:11 AM] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:354:13)
    at MDNSServer.sendOnAllNetworks (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:274:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:235:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:155:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
    at Timer.processTimers (timers.js:222:12)`

Not familiar with ciao but seems like both issues are associated with it.

**Comment by Brandawg93** [comment]
Homebridge v1.2.3 is no longer the latest. The team has downgraded back to v1.1.6 because of issues with ciao like these.

**Comment by geoffreyspencer** [comment]
Sorry to report that even with the latest update, Nest-Cam crashes after logging in. Same issue. It does log in, find my many Nest cameras but still an issue with Ciao as MikeGraben reports. From the status window:

[10/27/2020, 10:03:32 AM] [Nest-cam] Configuring accessory Access Side
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Back Hallway
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Backyard Door
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Basement
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Dining Room
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Doorbell Front Doorbell
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Driveway
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Entrance
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Family Room
[10/27/2020, 10:03:33 AM] [Nest-cam] Configuring accessory Front Hallway
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Garage Door Garage Doorbell
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Geoffrey's Bedroom
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Gym Gym
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Home Office
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Home Theatre
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Kitchen
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Kitchen Kitchen Display
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Living Room
[10/27/2020, 10:03:34 AM] [Nest-cam] Configuring accessory Patio Deck
[10/27/2020, 10:03:35 AM] [Nest-cam] Configuring accessory Pond
[10/27/2020, 10:03:35 AM] [Nest-cam] Configuring accessory Porch
[10/27/2020, 10:03:35 AM] [Nest-cam] Configuring accessory Service Side
[10/27/2020, 10:03:35 AM] [Nest-cam] Configuring accessory Shed Shed
[10/27/2020, 10:03:35 AM] [Nest-cam] Configuring accessory Upstairs Hallway
[10/27/2020, 10:03:37 AM] Error: Cannot update txt of service which is not announced yet. Received unannounced for service Homebridge 793B AF95._hap._tcp.local.
    at Responder.handleServiceRecordUpdate (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:410:13)
    at CiaoService.emit (events.js:198:13)
    at Timeout.txtTimer.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/CiaoService.ts:461:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[10/27/2020, 10:03:38 AM] Got SIGTERM, shutting down Homebridge...
[10/27/2020, 10:03:39 AM] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:354:13)
    at MDNSServer.sendOnAllNetworks (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:274:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:235:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:155:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
    at Timer.processTimers (timers.js:222:12)
[10/27/2020, 10:03:43 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/27/2020, 10:03:48 AM] [HB Supervisor] Restarting Homebridge...
[10/27/2020, 10:03:48 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/27/2020, 10:03:48 AM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 22797

**Comment by geoffreyspencer** [comment]
Question: How do I downgrade HomeBridge? Or is that done automatically?

**Comment by Brandawg93** [comment]
> [10/27/2020, 10:03:48 AM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 22797

@geoffreyspencer You are not using the latest version of homebridge.

`npm -g i homebridge@v1.1.6`

**Comment by geoffreyspencer** [comment]
Thanks Brandwag93. That was the problem. Homebridge and Ciao. Hopefully they will fix Homebridge or Ciao and I can upgrade to the latest version of HomeBridge.

**Comment by mikegraben** [comment]
Thanks @Brandawg93!
