### ISSUE TITLE
Nest Hello camera not responding

### ISSUE THREAD

**Issue by DavidSpek** [Brandawg93/homebridge-nest-cam#90]
**Describe the bug**

**To Reproduce**
Fresh installation(s), manual login procedure. The doorbell function did give a notification, but the video will not stream.

**Expected behavior**
Live video feed from the nest hello

Include with your bug report this version info:
```
node --version
v12.18.1
homebridge --version
1.1.1
```

```
[6/19/2020, 7:58:24 PM] [Nest-cam] [NexusStreamer] OK
[6/19/2020, 7:58:25 PM] [Nest-cam] [NexusStreamer] Playback Begin
[6/19/2020, 7:58:31 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:58:33 PM] [Nest-cam] RETURN AUDIO: received first frame
[6/19/2020, 7:58:38 PM] [Nest-cam] Received (unsupported) request to reconfigure to: {"width":1280,"height":720,"fps":30,"max_bit_rate":299,"rtcp_interval":0.5}
[6/19/2020, 7:58:41 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:58:43 PM] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[6/19/2020, 7:58:43 PM] [Nest-cam] Stopped streaming session!
[6/19/2020, 7:58:43 PM] [Nest-cam] [NexusStreamer] Playback End
[6/19/2020, 7:58:43 PM] [Nest-cam] [AUDIO] ffmpeg exited with code: null and signal: SIGKILL (AUDIO Stream stopped!)
[6/19/2020, 7:58:43 PM] [Nest-cam] [VIDEO] ffmpeg exited with code: null and signal: SIGKILL (VIDEO Stream stopped!)
[6/19/2020, 7:58:43 PM] [Nest-cam] [NexusStreamer] Disconnected
[6/19/2020, 7:58:45 PM] [Nest-cam] Updating info for Front Door
[6/19/2020, 7:58:51 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:59:01 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:59:11 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:59:21 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:59:31 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:59:41 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 7:59:45 PM] [Nest-cam] Updating info for Front Door
[6/19/2020, 7:59:51 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:00:01 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:00:11 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:00:21 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:00:31 PM] [Nest-cam] Checking for alerts on Front Door
```

**Comment by Brandawg93** [comment]
Nothing looks out-of-the-ordinary in the logs. What OS are you using?

**Comment by DavidSpek** [comment]
This is running in docker using oznu/docker-homebridge. I first tried it on siwatinc/homebridge_gui_unraid but got the same error. Host OS is unRAID.

**Comment by DavidSpek** [comment]
I just saw that is tried to reconfigure to another resolution as well. 

```
[6/19/2020, 8:04:32 PM] [Nest-cam] Received (unsupported) request to reconfigure to: {"width":640,"height":360,"fps":30,"max_bit_rate":132,"rtcp_interval":0.5}
```

**Comment by Brandawg93** [comment]
> I just saw that is tried to reconfigure to another resolution as well.
> 
> ```
> [6/19/2020, 8:04:32 PM] [Nest-cam] Received (unsupported) request to reconfigure to: {"width":640,"height":360,"fps":30,"max_bit_rate":132,"rtcp_interval":0.5}
> ```

That shouldn't be an issue. I don't let the plugin reconfigure to allow it to keep the quality sent from Nest.

It sounds like issues related to ffmpeg. Are you using a custom ffmpeg binary or the built-in ffmpeg?

**Comment by DavidSpek** [comment]
I haven't changed away from the default, so I'm guessing it should be using the built-in ffmpeg. I have an ffmpeg installation in /usr/bin/ffmpeg and /usr/local/bin/ffmpeg.

**Comment by DavidSpek** [comment]
The ffmpeg version that comes in the container is supposed to support libfdk_aac, however, if I specify it homebdrige gives an error saying it is not supported with that version of ffmpeg. When using `/usr/local/bin/ffmpeg` it doesn't give the libfdk_aac error but the error from the first post. Is it possible that it is because the image is running on Alpine instead of Ubuntu?

**Comment by Brandawg93** [comment]
None of the logs you see are an error. It may be a networking issue with ports. I ended up having to run my docker container in host mode because homebridge randomly assigns ports to different parts of the application. What mode are you running your docker container in?

**Comment by DavidSpek** [comment]
I am running it in host mode. With the built-in ffmpeg on Ubuntu it gives the same error as before. 
What kind of ports does it use? Does it access the Nest Hello directly on the network or would a port need to be forwarded? 

Just to be clear, the `AUDIO Stream stopped!` and and `VIDEO Stream stopped!` in the error happens while I am still viewing the "video" (which is actually just a very low-res image). It is not that I am closing the stream manually when it gives that response. 

```
[6/19/2020, 8:30:22 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:30:24 PM] [Nest-cam] VIDEO: received first frame
[6/19/2020, 8:30:24 PM] [Nest-cam] AUDIO: received first frame
[6/19/2020, 8:30:24 PM] [Nest-cam] waiting for socket to connect
[6/19/2020, 8:30:24 PM] [Nest-cam] waiting for socket to connect
[6/19/2020, 8:30:24 PM] [Nest-cam] [NexusStreamer] Connected
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] OK
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] Playback End
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] Redirect
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] Redirecting...
[6/19/2020, 8:30:25 PM] [Nest-cam] waiting for socket to connect
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] Playback End
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] Disconnected
[6/19/2020, 8:30:25 PM] [Nest-cam] [NexusStreamer] Connected
[6/19/2020, 8:30:26 PM] [Nest-cam] [NexusStreamer] OK
[6/19/2020, 8:30:27 PM] [Nest-cam] [NexusStreamer] Playback Begin
[6/19/2020, 8:30:32 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:30:34 PM] [Nest-cam] RETURN AUDIO: received first frame
[6/19/2020, 8:30:35 PM] [Nest-cam] Received (unsupported) request to reconfigure to: {"width":1280,"height":720,"fps":30,"max_bit_rate":299,"rtcp_interval":0.5}
[6/19/2020, 8:30:42 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:30:44 PM] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[6/19/2020, 8:30:44 PM] [Nest-cam] Stopped streaming session!
[6/19/2020, 8:30:44 PM] [Nest-cam] [AUDIO] ffmpeg exited with code: null and signal: SIGKILL (AUDIO Stream stopped!)
[6/19/2020, 8:30:44 PM] [Nest-cam] [VIDEO] ffmpeg exited with code: null and signal: SIGKILL (VIDEO Stream stopped!)
[6/19/2020, 8:30:44 PM] [Nest-cam] [NexusStreamer] Disconnected
```

**Comment by Brandawg93** [comment]
Ah. Then definitely an ffmpeg issue. I've published a test version of the plugin that enables ffmpeg debug output. You can install it via `npm -g i homebridge-nest-cam@test`. Try that and copy the output here.

**Comment by DavidSpek** [comment]
Here is the output:

```
[6/19/2020, 8:51:26 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:51:31 PM] [Nest-cam] VIDEO command: ffmpeg -f,h264,-use_wallclock_as_timestamps,1,-probesize,100000,-i,pipe:,-preset,ultrafast,-tune,zerolatency,-c:v,libx264,-payload_type,99,-ssrc,4964484,-f,rtp,-srtp_out_suite,AES_CM_128_HMAC_SHA1_80,-srtp_out_params,LdbcHlFlv7/5QiS5xA+0oHD2y9PD5UwxiMXCjzuu,srtp://192.168.178.144:59301?rtcpport=59301&localrtcpport=59301&pkt_size=1378
[6/19/2020, 8:51:31 PM] [Nest-cam] VIDEO: received first frame
[6/19/2020, 8:51:31 PM] [Nest-cam] VIDEO: ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Alpine 9.2.0)
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

[6/19/2020, 8:51:31 PM] [Nest-cam] AUDIO: received first frame
[6/19/2020, 8:51:31 PM] [Nest-cam] waiting for socket to connect
[6/19/2020, 8:51:31 PM] [Nest-cam] waiting for socket to connect
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] Connected
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] OK
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] Playback End
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] Redirect
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] Redirecting...
[6/19/2020, 8:51:31 PM] [Nest-cam] waiting for socket to connect
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] Disconnected
[6/19/2020, 8:51:31 PM] [Nest-cam] [NexusStreamer] Connected
[6/19/2020, 8:51:34 PM] [Nest-cam] [NexusStreamer] OK
[6/19/2020, 8:51:34 PM] [Nest-cam] [NexusStreamer] Playback Begin
[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: Input #0, h264, from 'pipe:':
  Duration: N/A, start: 
[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: 1592592694.702574, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1600x1200 [SAR 1:1 DAR 4:3], 15 fps, 15 tbr, 1200k tbn, 30 tbc

[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))

[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: [libx264 @ 0x55a42ab45400] using SAR=1/1

[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: [libx264 @ 0x55a42ab45400] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX

[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: [libx264 @ 0x55a42ab45400] profile Constrained Baseline, level 4.0, 4:2:0, 8-bit

[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: Output #0, rtp, to 'srtp://192.168.178.144:59301?rtcpport=59301&localrtcpport=59301&pkt_size=1378':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (libx264), yuvj420p(pc), 1600x1200 [SAR 1:1 DAR 4:3], q=-1--1, 15 fps, 90k tbn, 15 tbc
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1

[6/19/2020, 8:51:35 PM] [Nest-cam] VIDEO: frame=    4 fps=0.0 q=16.0 size=     150kB time=00:00:00.20 bitrate=6145.8kbits/s dup=0 drop=1 speed=0.383x    
[6/19/2020, 8:51:36 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:51:36 PM] [Nest-cam] VIDEO: frame=   12 fps= 11 q=16.0 size=     270kB time=00:00:00.73 bitrate=3018.6kbits/s dup=0 drop=2 speed=0.683x    
[6/19/2020, 8:51:36 PM] [Nest-cam] VIDEO: frame=   20 fps= 13 q=15.0 size=     385kB time=00:00:01.26 bitrate=2488.1kbits/s dup=0 drop=2 speed=0.794x    
[6/19/2020, 8:51:37 PM] [Nest-cam] VIDEO: frame=   28 fps= 13 q=13.0 size=     489kB time=00:00:01.80 bitrate=2226.1kbits/s dup=0 drop=2 speed=0.854x    
[6/19/2020, 8:51:37 PM] [Nest-cam] VIDEO: frame=   36 fps= 14 q=12.0 size=     601kB time=00:00:02.33 bitrate=2109.4kbits/s dup=0 drop=2 speed=0.877x    
[6/19/2020, 8:51:38 PM] [Nest-cam] VIDEO: frame=   44 fps= 14 q=13.0 size=     749kB time=00:00:02.86 bitrate=2140.2kbits/s dup=0 drop=2 speed=0.902x    
[6/19/2020, 8:51:39 PM] [Nest-cam] VIDEO: frame=   51 fps= 14 q=13.0 size=     829kB time=00:00:03.33 bitrate=2036.2kbits/s dup=0 drop=2 speed=0.89x    
[6/19/2020, 8:51:39 PM] [Nest-cam] VIDEO: frame=   61 fps= 14 q=14.0 size=    1061kB time=00:00:04.00 bitrate=2173.1kbits/s dup=1 drop=2 speed=0.94x    
[6/19/2020, 8:51:40 PM] [Nest-cam] VIDEO: frame=   74 fps= 15 q=13.0 size=    1259kB time=00:00:04.86 bitrate=2118.8kbits/s dup=1 drop=3 speed=1.02x    
[6/19/2020, 8:51:40 PM] [Nest-cam] VIDEO: frame=   83 fps= 16 q=13.0 size=    1370kB time=00:00:05.46 bitrate=2053.0kbits/s dup=1 drop=9 speed=1.03x    
[6/19/2020, 8:51:41 PM] [Nest-cam] VIDEO: frame=   91 fps= 16 q=13.0 size=    1479kB time=00:00:06.00 bitrate=2019.5kbits/s dup=1 drop=17 speed=1.03x    
[6/19/2020, 8:51:41 PM] [Nest-cam] RETURN AUDIO: received first frame
[6/19/2020, 8:51:41 PM] [Nest-cam] VIDEO: frame=   99 fps= 16 q=13.0 size=    1588kB time=00:00:06.53 bitrate=1991.4kbits/s dup=1 drop=25 speed=1.02x    
[6/19/2020, 8:51:42 PM] [Nest-cam] VIDEO: frame=  107 fps= 15 q=13.0 size=    1706kB time=00:00:07.06 bitrate=1977.9kbits/s dup=1 drop=33 speed=1.02x    
[6/19/2020, 8:51:42 PM] [Nest-cam] VIDEO: frame=  115 fps= 15 q=14.0 size=    1809kB time=00:00:07.60 bitrate=1950.4kbits/s dup=1 drop=41 speed=1.02x    
[6/19/2020, 8:51:43 PM] [Nest-cam] VIDEO: frame=  121 fps= 15 q=15.0 size=    1888kB time=00:00:08.00 bitrate=1933.5kbits/s dup=1 drop=47 speed=0.997x    
[6/19/2020, 8:51:43 PM] [Nest-cam] VIDEO: frame=  133 fps= 16 q=16.0 size=    2192kB time=00:00:08.80 bitrate=2040.9kbits/s dup=1 drop=56 speed=1.03x    
[6/19/2020, 8:51:44 PM] [Nest-cam] VIDEO: frame=  139 fps= 15 q=18.0 size=    2348kB time=00:00:09.20 bitrate=2091.1kbits/s dup=1 drop=65 speed=1.02x    
[6/19/2020, 8:51:44 PM] [Nest-cam] VIDEO: frame=  147 fps= 15 q=18.0 size=    2564kB time=00:00:09.73 bitrate=2157.8kbits/s dup=1 drop=73 speed=1.02x    
[6/19/2020, 8:51:45 PM] [Nest-cam] VIDEO: frame=  154 fps= 15 q=17.0 size=    2721kB time=00:00:10.20 bitrate=2185.5kbits/s dup=1 drop=80 speed=1.01x    
[6/19/2020, 8:51:45 PM] [Nest-cam] VIDEO: frame=  163 fps= 15 q=14.0 size=    3004kB time=00:00:10.80 bitrate=2278.5kbits/s dup=1 drop=86 speed=1.02x    
[6/19/2020, 8:51:46 PM] [Nest-cam] Checking for alerts on Front Door
[6/19/2020, 8:51:46 PM] [Nest-cam] VIDEO: frame=  170 fps= 15 q=13.0 size=    3138kB time=00:00:11.26 bitrate=2281.8kbits/s dup=1 drop=93 speed=1.01x    
[6/19/2020, 8:51:46 PM] [Nest-cam] VIDEO: frame=  178 fps= 15 q=14.0 size=    3247kB time=00:00:11.80 bitrate=2254.1kbits/s dup=1 drop=101 speed=1.01x    
[6/19/2020, 8:51:47 PM] [Nest-cam] VIDEO: frame=  186 fps= 15 q=14.0 size=    3371kB time=00:00:12.33 bitrate=2239.0kbits/s dup=1 drop=109 speed=1.01x    
[6/19/2020, 8:51:48 PM] [Nest-cam] VIDEO: frame=  194 fps= 15 q=14.0 size=    3478kB time=00:00:12.86 bitrate=2214.7kbits/s dup=1 drop=117 speed=1.01x    
[6/19/2020, 8:51:48 PM] [Nest-cam] VIDEO: frame=  202 fps= 15 q=14.0 size=    3576kB time=00:00:13.40 bitrate=2186.0kbits/s dup=1 drop=125 speed=1.01x    
[6/19/2020, 8:51:49 PM] [Nest-cam] VIDEO: frame=  210 fps= 15 q=14.0 size=    3668kB time=00:00:13.93 bitrate=2156.7kbits/s dup=1 drop=133 speed=1.01x    
[6/19/2020, 8:51:49 PM] [Nest-cam] VIDEO: frame=  218 fps= 15 q=14.0 size=    3786kB time=00:00:14.46 bitrate=2144.2kbits/s dup=1 drop=141 speed=1.01x    
[6/19/2020, 8:51:50 PM] [Nest-cam] VIDEO: frame=  225 fps= 15 q=13.0 size=    4029kB time=00:00:14.93 bitrate=2210.0kbits/s dup=1 drop=148 speed=1.01x    
[6/19/2020, 8:51:50 PM] [Nest-cam] VIDEO: frame=  233 fps= 15 q=13.0 size=    4131kB time=00:00:15.46 bitrate=2188.2kbits/s dup=1 drop=156 speed=1.01x    
[6/19/2020, 8:51:51 PM] [Nest-cam] VIDEO: frame=  241 fps= 15 q=14.0 size=    4265kB time=00:00:16.00 bitrate=2183.6kbits/s dup=2 drop=165 speed=1.01x    
[6/19/2020, 8:51:51 PM] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[6/19/2020, 8:51:51 PM] [Nest-cam] Stopped streaming session!
[6/19/2020, 8:51:51 PM] [Nest-cam] [AUDIO] ffmpeg exited with code: null and signal: SIGKILL (AUDIO Stream stopped gracefully.)
[6/19/2020, 8:51:51 PM] [Nest-cam] [VIDEO] ffmpeg exited with code: null and signal: SIGKILL (VIDEO Stream stopped gracefully.)
[6/19/2020, 8:51:51 PM] [Nest-cam] [NexusStreamer] Disconnected
```

**Comment by Brandawg93** [comment]
That looks completely normal to me. And you said it is disconnecting before you see the stream?

**Comment by DavidSpek** [comment]
The stream is a low-res static picture and if I press on it the loading circle appears and doesn't go away. After the ffmpeg error `[RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)` it says:
```
No response from camera
This camera is not responding
```

**Comment by Brandawg93** [comment]
Let me know if v3.1.0 fixes your issue.

**Comment by hugocarmona7** [comment]
I'm having the same issue.

`[6/22/2020, 21:16:14] [Nest-cam] [NexusStreamer] Connected
[6/22/2020, 21:16:14] [Nest-cam] [NexusStreamer] Redirecting...
[6/22/2020, 21:16:14] [Nest-cam] [NexusStreamer] Disconnected
[6/22/2020, 21:16:15] [Nest-cam] [NexusStreamer] Connected
[6/22/2020, 21:16:33] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[6/22/2020, 21:16:33] [Nest-cam] [NexusStreamer] Disconnected`

Just Installed v3.1.0 and still the same 

This is my system info 
![image](https://user-images.githubusercontent.com/25641898/85353540-1366fa80-b4ce-11ea-9c44-981cceec07ca.png)

**Comment by Brandawg93** [comment]
@hugocarmona7 If you disable audio by going into the camera’s accessories in the Home app and flipping the switch, does it work then? It seems to be an issue with 2-way audio for you.

**Comment by hugocarmona7** [comment]
> @hugocarmona7 If you disable audio by going into the camera’s accessories in the Home app and flipping the switch, does it work then? It seems to be an issue with 2-way audio for you.

Looks like something with iOS 13.5.1 (try deactivate and activate sound) because in iPadOS works flawlessly.

**Comment by Brandawg93** [comment]
Let me know if v3.2.0 fixes this issue. I think the issue was that the Return Audio stream was throwing an error causing the video and audio to stop as well.

**Comment by DavidSpek** [comment]
Still have the issues, both with and without the audio switch enabled in the config. Also tried disabling or disabling then enabling the audio or having disabled from the start and it doesn't load the video. FYI, I am running iOS 13.6, but it seems the issue is also there on iOS 13.5.1. I also have the issue on iPadOS (which should be the same as iOS though).

**Comment by Brandawg93** [comment]
Can you post your debug output with the audio disabled? `homebridge -D`

**Comment by Brandawg93** [comment]
I've published another test that should tell us why return audio is erroring. `npm -g i homebridge-nest-cam@test`. Instead of debug output with audio disabled, could you post output with audio enabled using the test?

Thanks for helping debug this.

**Comment by hugocarmona7** [comment]
> Let me know if v3.2.0 fixes this issue. I think the issue was that the Return Audio stream was throwing an error causing the video and audio to stop as well.

The new version also broken iPadOS 14, yesterday this war working correctly

**Comment by Brandawg93** [comment]
@hugocarmona7 Homebridge isn't updated for beta HomeKit, so there is nothing I can do about iOS 14.

**Comment by DavidSpek** [comment]
So I still have the audio switch disabled in the config, but this is the output. 

```
[6/23/2020, 3:30:07 PM] [Nest-cam] [NexusStreamer] Connected
[6/23/2020, 3:30:08 PM] [Nest-cam] [NexusStreamer] OK
[6/23/2020, 3:30:09 PM] [Nest-cam] [NexusStreamer] Playback Begin
[6/23/2020, 3:30:15 PM] [Nest-cam] Checking for alerts on Front Door
[6/23/2020, 3:30:17 PM] [Nest-cam] RETURN AUDIO: received first frame
[6/23/2020, 3:30:17 PM] [Nest-cam] RETURN AUDIO: Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:0':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 16000 Hz, mono, s16

[6/23/2020, 3:30:17 PM] [Nest-cam] RETURN AUDIO: Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> speex (libspeex))

[6/23/2020, 3:30:25 PM] [Nest-cam] Checking for alerts on Front Door
[6/23/2020, 3:30:27 PM] [Nest-cam] RETURN AUDIO: pipe:0: Operation timed out

[6/23/2020, 3:30:27 PM] [Nest-cam] RETURN AUDIO: Output #0, data, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.29.100

[6/23/2020, 3:30:27 PM] [Nest-cam] RETURN AUDIO:     Stream #0:0: Audio: speex (libspeex), 16000 Hz, mono, s16, 23 kb/s
    Metadata:
      encoder         : Lavc58.54.100 libspeex
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

[6/23/2020, 3:30:27 PM] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[6/23/2020, 3:30:35 PM] [Nest-cam] Checking for alerts on Front Door
```

**Comment by Brandawg93** [comment]
> [6/23/2020, 3:30:27 PM] [Nest-cam] RETURN AUDIO: pipe:0: Operation timed out
There is definitely something wrong with that. I've published a new test. Let me know if it helps.

**Comment by DavidSpek** [comment]
Audio still disabled in config, same issue with the video not loading. 

```
[6/23/2020, 3:54:20 PM] [Nest-cam] VIDEO: received first frame
[6/23/2020, 3:54:20 PM] [Nest-cam] AUDIO: received first frame
[6/23/2020, 3:54:20 PM] [Nest-cam] waiting for socket to connect
[6/23/2020, 3:54:20 PM] [Nest-cam] waiting for socket to connect
[6/23/2020, 3:54:20 PM] [Nest-cam] [NexusStreamer] Connected
[6/23/2020, 3:54:21 PM] [Nest-cam] [NexusStreamer] OK
[6/23/2020, 3:54:21 PM] [Nest-cam] [NexusStreamer] Playback End
[6/23/2020, 3:54:21 PM] [Nest-cam] [NexusStreamer] Redirect
[6/23/2020, 3:54:21 PM] [Nest-cam] [NexusStreamer] Redirecting...
[6/23/2020, 3:54:21 PM] [Nest-cam] waiting for socket to connect
[6/23/2020, 3:54:21 PM] [Nest-cam] [NexusStreamer] Disconnected
[6/23/2020, 3:54:21 PM] [Nest-cam] [NexusStreamer] Connected
[6/23/2020, 3:54:22 PM] [Nest-cam] Checking for alerts on Front Door
[6/23/2020, 3:54:30 PM] [Nest-cam] RETURN AUDIO: received first frame
[6/23/2020, 3:54:32 PM] [Nest-cam] Checking for alerts on Front Door
[6/23/2020, 3:54:33 PM] [Nest-cam] [NexusStreamer] OK
[6/23/2020, 3:54:33 PM] [Nest-cam] [NexusStreamer] Playback Begin
[6/23/2020, 3:54:40 PM] [Nest-cam] [RETURN AUDIO] ffmpeg exited with code: 0 and signal: null (error)
[6/23/2020, 3:54:42 PM] [Nest-cam] Checking for alerts on Front Door
[6/23/2020, 3:54:52 PM] [Nest-cam] Checking for alerts on Front Door
[6/23/2020, 3:54:53 PM] [Nest-cam] Stopped streaming session!
[6/23/2020, 3:54:53 PM] [Nest-cam] [AUDIO] ffmpeg exited with code: null and signal: SIGKILL (AUDIO Stream stopped gracefully.)
[6/23/2020, 3:54:53 PM] [Nest-cam] [VIDEO] ffmpeg exited with code: null and signal: SIGKILL (VIDEO Stream stopped gracefully.)
[6/23/2020, 3:54:53 PM] [Nest-cam] [NexusStreamer] Disconnected
[6/23/2020, 3:54:56 PM] [Nest-cam] Updating info for Front Door
```

**Comment by Brandawg93** [comment]
I was finally able to reproduce the error on my end. It seems to be a port issue. I'm guessing something is blocking your video port. I've published a new test that will output the ports being used. Could you post that here?

**Comment by Brandawg93** [comment]
After much research, I've found the issue. Your return audio is not receiving data, so it is killing the process. I've set up a function to ping the return audio process to hopefully keep it alive. Let me know if the latest test works for you.

**Comment by Brandawg93** [comment]
v3.2.1 may fix the issue. Let me know if you try it.

**Comment by Brandawg93** [comment]
This should be fixed in v3.2.2. If not, feel free to reopen this issue.

**Comment by Prakkie** [comment]
I am running latest version v3.5.0 and seeing same problem

![image](https://user-images.githubusercontent.com/22531207/88707243-38ebb300-d0cf-11ea-86ce-967321b33b15.png)
